version: "3"
services:
  firestore-proxy-dev:
    build: .
    image: trendev/firestore-proxy:dev
    container_name: firestore-proxy-dev
    environment:
      - NODE_ENV=dev
    ports:
      - 9000:9000