version: '3'
services:
  firestore-proxy-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: trendev/firestore-proxy:dev
    container_name: firestore-proxy-dev
    ports:
      - 9000:9000