version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: build
          command: docker build -t trendev/firestore-proxy .
      - run:
          name : login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: push
          command: docker push trendev/firestore-proxy
