version: 2
jobs:
  build_master:
    environment:
      IMAGE_NAME : trendev/firestore-proxy
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: docker build
          command: DOCKER_BUILDKIT=1 docker build -t $IMAGE_NAME --build-arg BUILDKIT_INLINE_CACHE=1 .
      - run:
          name: docker tag
          command: docker tag $IMAGE_NAME $IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker push lastest
          command: docker push $IMAGE_NAME:latest
      - run:
          name: docker push $CIRCLE_SHA1
          command: docker push $IMAGE_NAME:$CIRCLE_SHA1
  build: # generic job for other branches
    environment:
      IMAGE_NAME : trendev/firestore-proxy
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: docker build
          # command: DOCKER_BUILDKIT=1 docker build -t $IMAGE_NAME:$CIRCLE_BRANCH -f $CIRCLE_BRANCH.Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1 .
          command: DOCKER_BUILDKIT=1 docker build -t $IMAGE_NAME:$CIRCLE_BRANCH -f Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1 .
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker push
          command: docker push $IMAGE_NAME:$CIRCLE_BRANCH
workflows:
  version: 2
  commit:
    jobs:
      - build_master:
          filters:
            branches:
              only: master
      - build:
          filters:
            branches:
              only:
                - preprod
                # - preview
