version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: build firestore-proxy
          command: docker build -t trendev/firestore-proxy .