version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: build PRODUCTION image
          command: docker build -t trendev/firestore-proxy .
      - run:
          name : docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: push PRODUCTION image
          command: docker push -t -t trendev/firestore-proxy
